name = "LCEFromData"
uuid = "8b5d6e6e-ed3c-4bac-af88-1410c1426d23"
authors = ["Jadon Clugston <jadonclugston@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
